name: "Zgłoszenie luki bezpieczeństwa"
description: "Zgłoś potencjalną lukę bezpieczeństwa w motywie"
title: "[Bezpieczeństwo]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: "Nie publikuj wrażliwych informacji publicznie. W razie poważnej luki — napisz bezpośrednio na e-mail: security@twojadomena.pl"
  - type: textarea
    id: details
    attributes:
      label: "Opis potencjalnej luki"
      placeholder: "Opis, jak można wykorzystać lukę..."
